#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, homogeneous array and size immutable, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

Why pandas:
1. import data from different formats liks csv, excel.
2. Data Cleaning: Used for detecting missing values and invalid values.
3. Size mutability: We can add or delete from a dataset
4. Reshaping and pivoting of datasets.
5. Effective manipulation and extraction.
6. Statistical analysis

In [1]:
import pandas as pd

In [1]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

/var/folders/wp/9w_2m0xn5clfmrkfxjxl7cm00000gn/T/ipykernel_38199/58280681.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
series.values

array([1, 2, 3, 4, 5])

In [5]:
series.name="numbers"
series

0    1
1    2
2    3
3    4
4    5
Name: numbers, dtype: int64

In [6]:
series.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
series[1]

2

In [9]:
series[0:2]

0    1
1    2
Name: numbers, dtype: int64

In [10]:
# iloc -> Location based indexing
series.iloc[3]

4

In [14]:
series.iloc[[1, 3, 4]]

1    2
3    4
4    5
Name: numbers, dtype: int64

In [15]:
series.name = "calories"
series.index = ["apple", "banana", "grapes", "orange", "strawberry"]
series.index.name = "fruits"
series

fruits
apple         1
banana        2
grapes        3
orange        4
strawberry    5
Name: calories, dtype: int64

In [16]:
series["grapes"]

3

In [21]:
print(series.iloc[2])
print("*"*20)
print(series.loc["grapes"])
print("*"*20)
print(series.loc["apple":"orange"])
print("*"*20)
print(series.loc[["apple","orange"]])
print("*"*20)
print(series.loc[series>2])
print("*"*20)
print(series.loc[series<=2])
print("*"*20)

3
********************
3
********************
fruits
apple     1
banana    2
grapes    3
orange    4
Name: calories, dtype: int64
********************
fruits
apple     1
orange    4
Name: calories, dtype: int64
********************
fruits
grapes        3
orange        4
strawberry    5
Name: calories, dtype: int64
********************
fruits
apple     1
banana    2
Name: calories, dtype: int64
********************

In [22]:
# In label based indexing, your start as well as stop value both are included in the result.
series["apple":"orange"]

fruits
apple     1
banana    2
grapes    3
orange    4
Name: calories, dtype: int64

In [2]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [24]:
# Conditional selection
series_dict[series_dict>=2]

b    2
c    3
dtype: int64

In [25]:
# Logical selection
series_dict[(series_dict>=2)&(series_dict<=3)]

b    2
c    3
dtype: int64

In [29]:
# Modifying the series
series_dict["b"] = "d"
series_dict

a    1
b    d
c    3
dtype: object

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [34]:
import numpy as np
series=  pd.Series(['a', np.nan, 1, np.nan, 2])
print(series.notnull())
print(series.notnull().sum())

0     True
1    False
2     True
3    False
4     True
dtype: bool
3

## Dataframe

In [15]:
## create a Dataframe from a dictionary oof list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [8]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [37]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [38]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [17]:
### Accessing Data From Dataframe
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [39]:
df['Category']

0     A
1     B
2     C
3     B
4     B
5     B
6     A
7     C
8     C
9     A
10    B
11    B
12    A
13    A
14    A
15    C
16    C
17    C
18    A
19    A
20    C
21    C
22    B
23    C
24    A
25    C
26    C
27    C
28    B
29    C
30    B
31    A
32    B
33    C
34    C
35    B
36    C
37    C
38    C
39    A
40    B
41    C
42    A
43    A
44    A
45    B
46    B
47    B
48    C
49    C
Name: Category, dtype: object

In [50]:
df[['Category', 'Value']]

   Category  Value
0         A   28.0
1         B   39.0
2         C   32.0
3         B    8.0
4         B   26.0
5         B   54.0
6         A   16.0
7         C   89.0
8         C   37.0
9         A   22.0
10        B    7.0
11        B   60.0
12        A   70.0
13        A   69.0
14        A   47.0
15        C    NaN
16        C   93.0
17        C    NaN
18        A   31.0
19        A   59.0
20        C   82.0
21        C   37.0
22        B   62.0
23        C   92.0
24        A   24.0
25        C   95.0
26        C   71.0
27        C   56.0
28        B    NaN
29        C   51.0
30        B   50.0
31        A   17.0
32        B   63.0
33        C   27.0
34        C   70.0
35        B   60.0
36        C   36.0
37        C    2.0
38        C   94.0
39        A   62.0
40        B   15.0
41        C   97.0
42        A   93.0
43        A   43.0
44        A   96.0
45        B   99.0
46        B    6.0
47        B   69.0
48        C   65.0
49        C   11.0

In [40]:
df.loc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [41]:
df.iloc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [44]:
df.loc[0:3]

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East

In [43]:
df.loc[0:3, ['Product','Category']]

    Product Category
0  Product1        A
1  Product3        B
2  Product2        C
3  Product1        B

In [48]:
df.iloc[0:3, :2] # rows, columns

         Date Category
0  2023-01-01        A
1  2023-01-02        B
2  2023-01-03        C

In [35]:
## Accessing a specified element
df.at[2,'Age']

45

In [36]:
df.at[2,'Name']

'Jack'

In [38]:
## Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [39]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [40]:
### Data MAnipulation with Dataframe
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [41]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

    Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30   New York   60000
2   Jack   45    Florida   70000

In [46]:
## Remove a column
# For removing the column, the axis is 1
# For removing the row, the axis is 0
df.drop('Salary',axis=1,inplace=True)

In [47]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [48]:
## Broadcasting
## Add age to the column
df['Age']=df['Age']+1
df

    Name  Age       City
0  Krish   26  Bangalore
1   John   31   New York
2   Jack   46    Florida

In [51]:
df.drop(0,inplace=True)

In [52]:
df

   Name  Age      City
1  John   31  New York
2  Jack   46   Florida

In [53]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [54]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [55]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [52]:
df.shape

(50, 6)

In [53]:
# Renaming a column
df.rename(columns={'Category': 'Category_New'}, inplace=True)
df
# Renaming a row
df.rename(index={0: 'First', 1: 'Second'}, inplace=True)
df

              Date Category_New  Value   Product  Sales Region
First   2023-01-01            A   28.0  Product1  754.0   East
Second  2023-01-02            B   39.0  Product3  110.0  North
2       2023-01-03            C   32.0  Product2  398.0   East
3       2023-01-04            B    8.0  Product1  522.0   East
4       2023-01-05            B   26.0  Product3  869.0  North
5       2023-01-06            B   54.0  Product3  192.0   West
6       2023-01-07            A   16.0  Product1  936.0   East
7       2023-01-08            C   89.0  Product1  488.0   West
8       2023-01-09            C   37.0  Product3  772.0   West
9       2023-01-10            A   22.0  Product2  834.0   West
10      2023-01-11            B    7.0  Product1  842.0  North
11      2023-01-12            B   60.0  Product2    NaN   West
12      2023-01-13            A   70.0  Product3  628.0  South
13      2023-01-14            A   69.0  Product1  423.0   East
14      2023-01-15            A   47.0  Product2  893.0   West
15      2023-01-16            C    NaN  Product1  895.0  North
16      2023-01-17            C   93.0  Product2  511.0  South
17      2023-01-18            C    NaN  Product1  108.0   West
18      2023-01-19            A   31.0  Product2  578.0   West
19      2023-01-20            A   59.0  Product1  736.0   East
20      2023-01-21            C   82.0  Product3  606.0  South
21      2023-01-22            C   37.0  Product2  992.0  South
22      2023-01-23            B   62.0  Product3  942.0  North
23      2023-01-24            C   92.0  Product2  342.0   West
24      2023-01-25            A   24.0  Product2  458.0   East
25      2023-01-26            C   95.0  Product1  584.0   West
26      2023-01-27            C   71.0  Product2  619.0  North
27      2023-01-28            C   56.0  Product2  224.0  North
28      2023-01-29            B    NaN  Product3  617.0  North
29      2023-01-30            C   51.0  Product2  737.0  South
30      2023-01-31            B   50.0  Product3  735.0   West
31      2023-02-01            A   17.0  Product2  189.0   West
32      2023-02-02            B   63.0  Product3  338.0  South
33      2023-02-03            C   27.0  Product3    NaN   East
34      2023-02-04            C   70.0  Product3  669.0   West
35      2023-02-05            B   60.0  Product2    NaN   West
36      2023-02-06            C   36.0  Product3  177.0   East
37      2023-02-07            C    2.0  Product1    NaN  North
38      2023-02-08            C   94.0  Product1  408.0  South
39      2023-02-09            A   62.0  Product1  155.0   West
40      2023-02-10            B   15.0  Product1  578.0   East
41      2023-02-11            C   97.0  Product1  256.0   East
42      2023-02-12            A   93.0  Product3  164.0   West
43      2023-02-13            A   43.0  Product3  949.0   East
44      2023-02-14            A   96.0  Product3  830.0   East
45      2023-02-15            B   99.0  Product2  599.0   West
46      2023-02-16            B    6.0  Product1  938.0  South
47      2023-02-17            B   69.0  Product3  143.0   West
48      2023-02-18            C   65.0  Product3  182.0  North
49      2023-02-19            C   11.0  Product3  708.0  North

In [54]:
df['Category_New'].unique()

array(['A', 'B', 'C'], dtype=object)

In [55]:
df['Category_New'].value_counts()

Category_New
C    21
B    15
A    14
Name: count, dtype: int64

In [56]:
## Data Cleaning
df.isnull().sum()

Date            0
Category_New    0
Value           3
Product         0
Sales           4
Region          0
dtype: int64

In [59]:
# Drop null values rows
# Use dropna for getting rid of them
df.dropna(how="any") # any row value is null
df.dropna(how="all") # all row value is null
df.dropna(subset=["Category_New"]) # only Category_New column value is null
df
df.isnull().sum()

Date            0
Category_New    0
Value           3
Product         0
Sales           4
Region          0
dtype: int64

In [60]:
# Use fillna for replacing the null values
df.fillna(0)

              Date Category_New  Value   Product  Sales Region
First   2023-01-01            A   28.0  Product1  754.0   East
Second  2023-01-02            B   39.0  Product3  110.0  North
2       2023-01-03            C   32.0  Product2  398.0   East
3       2023-01-04            B    8.0  Product1  522.0   East
4       2023-01-05            B   26.0  Product3  869.0  North
5       2023-01-06            B   54.0  Product3  192.0   West
6       2023-01-07            A   16.0  Product1  936.0   East
7       2023-01-08            C   89.0  Product1  488.0   West
8       2023-01-09            C   37.0  Product3  772.0   West
9       2023-01-10            A   22.0  Product2  834.0   West
10      2023-01-11            B    7.0  Product1  842.0  North
11      2023-01-12            B   60.0  Product2    0.0   West
12      2023-01-13            A   70.0  Product3  628.0  South
13      2023-01-14            A   69.0  Product1  423.0   East
14      2023-01-15            A   47.0  Product2  893.0   West
15      2023-01-16            C    0.0  Product1  895.0  North
16      2023-01-17            C   93.0  Product2  511.0  South
17      2023-01-18            C    0.0  Product1  108.0   West
18      2023-01-19            A   31.0  Product2  578.0   West
19      2023-01-20            A   59.0  Product1  736.0   East
20      2023-01-21            C   82.0  Product3  606.0  South
21      2023-01-22            C   37.0  Product2  992.0  South
22      2023-01-23            B   62.0  Product3  942.0  North
23      2023-01-24            C   92.0  Product2  342.0   West
24      2023-01-25            A   24.0  Product2  458.0   East
25      2023-01-26            C   95.0  Product1  584.0   West
26      2023-01-27            C   71.0  Product2  619.0  North
27      2023-01-28            C   56.0  Product2  224.0  North
28      2023-01-29            B    0.0  Product3  617.0  North
29      2023-01-30            C   51.0  Product2  737.0  South
30      2023-01-31            B   50.0  Product3  735.0   West
31      2023-02-01            A   17.0  Product2  189.0   West
32      2023-02-02            B   63.0  Product3  338.0  South
33      2023-02-03            C   27.0  Product3    0.0   East
34      2023-02-04            C   70.0  Product3  669.0   West
35      2023-02-05            B   60.0  Product2    0.0   West
36      2023-02-06            C   36.0  Product3  177.0   East
37      2023-02-07            C    2.0  Product1    0.0  North
38      2023-02-08            C   94.0  Product1  408.0  South
39      2023-02-09            A   62.0  Product1  155.0   West
40      2023-02-10            B   15.0  Product1  578.0   East
41      2023-02-11            C   97.0  Product1  256.0   East
42      2023-02-12            A   93.0  Product3  164.0   West
43      2023-02-13            A   43.0  Product3  949.0   East
44      2023-02-14            A   96.0  Product3  830.0   East
45      2023-02-15            B   99.0  Product2  599.0   West
46      2023-02-16            B    6.0  Product1  938.0  South
47      2023-02-17            B   69.0  Product3  143.0   West
48      2023-02-18            C   65.0  Product3  182.0  North
49      2023-02-19            C   11.0  Product3  708.0  North

In [61]:
df["Sales"].fillna(df["Sales"].mean())

First     754.000000
Second    110.000000
2         398.000000
3         522.000000
4         869.000000
5         192.000000
6         936.000000
7         488.000000
8         772.000000
9         834.000000
10        842.000000
11        557.130435
12        628.000000
13        423.000000
14        893.000000
15        895.000000
16        511.000000
17        108.000000
18        578.000000
19        736.000000
20        606.000000
21        992.000000
22        942.000000
23        342.000000
24        458.000000
25        584.000000
26        619.000000
27        224.000000
28        617.000000
29        737.000000
30        735.000000
31        189.000000
32        338.000000
33        557.130435
34        669.000000
35        557.130435
36        177.000000
37        557.130435
38        408.000000
39        155.000000
40        578.000000
41        256.000000
42        164.000000
43        949.000000
44        830.000000
45        599.000000
46        938.000000
47        143.000000
48        182.000000
49        708.000000
Name: Sales, dtype: float64

In [62]:
# Instead of ffilling with the default values, we can use forward fill and backward fill
# Forward fill means that the null value will be replaced with the previous value
df.fillna(method="ffill")
# Backward fill means that the null value will be replaced with the next value
df.fillna(method="bfill")

# Problem with the Forward fill is if the first value is null, then next values also will be null.

/var/folders/wp/9w_2m0xn5clfmrkfxjxl7cm00000gn/T/ipykernel_38199/354375578.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")
/var/folders/wp/9w_2m0xn5clfmrkfxjxl7cm00000gn/T/ipykernel_38199/354375578.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

              Date Category_New  Value   Product  Sales Region
First   2023-01-01            A   28.0  Product1  754.0   East
Second  2023-01-02            B   39.0  Product3  110.0  North
2       2023-01-03            C   32.0  Product2  398.0   East
3       2023-01-04            B    8.0  Product1  522.0   East
4       2023-01-05            B   26.0  Product3  869.0  North
5       2023-01-06            B   54.0  Product3  192.0   West
6       2023-01-07            A   16.0  Product1  936.0   East
7       2023-01-08            C   89.0  Product1  488.0   West
8       2023-01-09            C   37.0  Product3  772.0   West
9       2023-01-10            A   22.0  Product2  834.0   West
10      2023-01-11            B    7.0  Product1  842.0  North
11      2023-01-12            B   60.0  Product2  628.0   West
12      2023-01-13            A   70.0  Product3  628.0  South
13      2023-01-14            A   69.0  Product1  423.0   East
14      2023-01-15            A   47.0  Product2  893.0   West
15      2023-01-16            C   93.0  Product1  895.0  North
16      2023-01-17            C   93.0  Product2  511.0  South
17      2023-01-18            C   31.0  Product1  108.0   West
18      2023-01-19            A   31.0  Product2  578.0   West
19      2023-01-20            A   59.0  Product1  736.0   East
20      2023-01-21            C   82.0  Product3  606.0  South
21      2023-01-22            C   37.0  Product2  992.0  South
22      2023-01-23            B   62.0  Product3  942.0  North
23      2023-01-24            C   92.0  Product2  342.0   West
24      2023-01-25            A   24.0  Product2  458.0   East
25      2023-01-26            C   95.0  Product1  584.0   West
26      2023-01-27            C   71.0  Product2  619.0  North
27      2023-01-28            C   56.0  Product2  224.0  North
28      2023-01-29            B   51.0  Product3  617.0  North
29      2023-01-30            C   51.0  Product2  737.0  South
30      2023-01-31            B   50.0  Product3  735.0   West
31      2023-02-01            A   17.0  Product2  189.0   West
32      2023-02-02            B   63.0  Product3  338.0  South
33      2023-02-03            C   27.0  Product3  669.0   East
34      2023-02-04            C   70.0  Product3  669.0   West
35      2023-02-05            B   60.0  Product2  177.0   West
36      2023-02-06            C   36.0  Product3  177.0   East
37      2023-02-07            C    2.0  Product1  408.0  North
38      2023-02-08            C   94.0  Product1  408.0  South
39      2023-02-09            A   62.0  Product1  155.0   West
40      2023-02-10            B   15.0  Product1  578.0   East
41      2023-02-11            C   97.0  Product1  256.0   East
42      2023-02-12            A   93.0  Product3  164.0   West
43      2023-02-13            A   43.0  Product3  949.0   East
44      2023-02-14            A   96.0  Product3  830.0   East
45      2023-02-15            B   99.0  Product2  599.0   West
46      2023-02-16            B    6.0  Product1  938.0  South
47      2023-02-17            B   69.0  Product3  143.0   West
48      2023-02-18            C   65.0  Product3  182.0  North
49      2023-02-19            C   11.0  Product3  708.0  North

In [63]:
# Duplicates
df_duplicates = df[df.duplicated()]
df_duplicates
# if you want the first duplicated values and remove the next one
df_duplicates = df[df.duplicated(keep='first')]
df_duplicates
# if you want the last duplicated values and remove the first one
df_duplicates = df[df.duplicated(keep='last')]
df_duplicates

Empty DataFrame
Columns: [Date, Category_New, Value, Product, Sales, Region]
Index: []

In [67]:
# invalid values
df["Updated Value"] = df["Value"].apply(lambda x: x*2 if x > 50.0 else x) 
df

              Date Category_New  Value   Product  Sales Region  Updated Value
First   2023-01-01            A   28.0  Product1  754.0   East           28.0
Second  2023-01-02            B   39.0  Product3  110.0  North           39.0
2       2023-01-03            C   32.0  Product2  398.0   East           32.0
3       2023-01-04            B    8.0  Product1  522.0   East            8.0
4       2023-01-05            B   26.0  Product3  869.0  North           26.0
5       2023-01-06            B   54.0  Product3  192.0   West          108.0
6       2023-01-07            A   16.0  Product1  936.0   East           16.0
7       2023-01-08            C   89.0  Product1  488.0   West          178.0
8       2023-01-09            C   37.0  Product3  772.0   West           37.0
9       2023-01-10            A   22.0  Product2  834.0   West           22.0
10      2023-01-11            B    7.0  Product1  842.0  North            7.0
11      2023-01-12            B   60.0  Product2    NaN   West          120.0
12      2023-01-13            A   70.0  Product3  628.0  South          140.0
13      2023-01-14            A   69.0  Product1  423.0   East          138.0
14      2023-01-15            A   47.0  Product2  893.0   West           47.0
15      2023-01-16            C    NaN  Product1  895.0  North            NaN
16      2023-01-17            C   93.0  Product2  511.0  South          186.0
17      2023-01-18            C    NaN  Product1  108.0   West            NaN
18      2023-01-19            A   31.0  Product2  578.0   West           31.0
19      2023-01-20            A   59.0  Product1  736.0   East          118.0
20      2023-01-21            C   82.0  Product3  606.0  South          164.0
21      2023-01-22            C   37.0  Product2  992.0  South           37.0
22      2023-01-23            B   62.0  Product3  942.0  North          124.0
23      2023-01-24            C   92.0  Product2  342.0   West          184.0
24      2023-01-25            A   24.0  Product2  458.0   East           24.0
25      2023-01-26            C   95.0  Product1  584.0   West          190.0
26      2023-01-27            C   71.0  Product2  619.0  North          142.0
27      2023-01-28            C   56.0  Product2  224.0  North          112.0
28      2023-01-29            B    NaN  Product3  617.0  North            NaN
29      2023-01-30            C   51.0  Product2  737.0  South          102.0
30      2023-01-31            B   50.0  Product3  735.0   West           50.0
31      2023-02-01            A   17.0  Product2  189.0   West           17.0
32      2023-02-02            B   63.0  Product3  338.0  South          126.0
33      2023-02-03            C   27.0  Product3    NaN   East           27.0
34      2023-02-04            C   70.0  Product3  669.0   West          140.0
35      2023-02-05            B   60.0  Product2    NaN   West          120.0
36      2023-02-06            C   36.0  Product3  177.0   East           36.0
37      2023-02-07            C    2.0  Product1    NaN  North            2.0
38      2023-02-08            C   94.0  Product1  408.0  South          188.0
39      2023-02-09            A   62.0  Product1  155.0   West          124.0
40      2023-02-10            B   15.0  Product1  578.0   East           15.0
41      2023-02-11            C   97.0  Product1  256.0   East          194.0
42      2023-02-12            A   93.0  Product3  164.0   West          186.0
43      2023-02-13            A   43.0  Product3  949.0   East           43.0
44      2023-02-14            A   96.0  Product3  830.0   East          192.0
45      2023-02-15            B   99.0  Product2  599.0   West          198.0
46      2023-02-16            B    6.0  Product1  938.0  South            6.0
47      2023-02-17            B   69.0  Product3  143.0   West          138.0
48      2023-02-18            C   65.0  Product3  182.0  North          130.0
49      2023-02-19            C   11.0  Product3  708.0  North           11.0

In [ ]:
## Joins and Merge
# Joins: Left join, right join, outer join and inner join
# Merge: Inner join

df1 = {}
df2 = {}
pd.concat([df1, df2], axis=1)

# merging the common column in both the dataframes
pd.merge(df1, df2, on="Dept")